import { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import {
  BookOpen,
  Settings,
  MessageSquare,
  TestTube,
  Upload,
  FileText,
  Trash2,
  RefreshCw,
  Check,
  AlertCircle,
  Send,
  Bot,
  Zap,
  Brain,
  Sparkles,
  Plus,
} from 'lucide-react';
import { MainLayout } from '../../components/layout';
import {
  Card,
  Button,
  Tabs,
  TabsList,
  TabsTrigger,
  TabsContent,
  Progress,
  Slider,
  Badge,
  Textarea,
  Avatar,
} from '../../components/ui';

const knowledgeBases = [
  {
    id: '1',
    name: 'Product FAQ',
    description: 'Common questions about products',
    documentCount: 156,
    lastUpdated: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    status: 'ready' as const,
  },
  {
    id: '2',
    name: 'Customer Support',
    description: 'Support tickets and resolutions',
    documentCount: 89,
    lastUpdated: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    status: 'training' as const,
    progress: 67,
  },
  {
    id: '3',
    name: 'Policy Documents',
    description: 'Terms, privacy, and policies',
    documentCount: 24,
    lastUpdated: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000),
    status: 'ready' as const,
  },
  {
    id: '4',
    name: 'Technical Docs',
    description: 'API and integration guides',
    documentCount: 45,
    lastUpdated: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    status: 'error' as const,
  },
];

const aiModels = [
  {
    id: 'gpt-4',
    name: 'GPT-4 Turbo',
    description: 'Most capable model, best for complex tasks',
    version: '4.0-turbo',
    capabilities: ['Complex reasoning', 'Code generation', 'Creative writing'],
    isSelected: true,
  },
  {
    id: 'gpt-3.5',
    name: 'GPT-3.5 Turbo',
    description: 'Fast and efficient for most tasks',
    version: '3.5-turbo',
    capabilities: ['General chat', 'Quick responses', 'Cost effective'],
    isSelected: false,
  },
  {
    id: 'claude',
    name: 'Claude 3',
    description: 'Excellent for analysis and safety',
    version: '3.0-opus',
    capabilities: ['Long context', 'Analysis', 'Safe responses'],
    isSelected: false,
  },
];

const testMessages = [
  { role: 'user' as const, content: 'What is your return policy?' },
  {
    role: 'ai' as const,
    content:
      'Our return policy allows customers to return items within 30 days of purchase for a full refund. Items must be in original condition with all tags attached. To initiate a return, please visit our returns portal or contact customer support.',
  },
];

export function AIAssistant() {
  const [modelConfig, setModelConfig] = useState({
    temperature: 0.7,
    maxTokens: 2048,
    topP: 0.9,
    frequencyPenalty: 0,
    presencePenalty: 0,
  });
  const [systemPrompt, setSystemPrompt] = useState(
    `You are a helpful customer service assistant for our e-commerce platform.

Guidelines:
- Be friendly, professional, and concise
- Always try to resolve customer issues
- If you cannot help, offer to connect with a human agent
- Use the knowledge base to provide accurate information
- Never make promises you cannot keep`
  );
  const [testInput, setTestInput] = useState('');
  const [testConversation, setTestConversation] = useState(testMessages);

  const handleSendTest = () => {
    if (!testInput.trim()) return;
    setTestConversation([
      ...testConversation,
      { role: 'user', content: testInput },
      {
        role: 'ai',
        content:
          'This is a simulated AI response. In production, this would be generated by the selected AI model using the configured parameters and system prompt.',
      },
    ]);
    setTestInput('');
  };

  return (
    <MainLayout title="AI Assistant" subtitle="Configure and manage your AI assistant">
      <div className="flex gap-6">
        <div className="flex-1">
          <Tabs defaultValue="knowledge" className="space-y-6">
            <TabsList>
              <TabsTrigger value="knowledge" icon={<BookOpen className="w-4 h-4" />}>
                Knowledge Base
              </TabsTrigger>
              <TabsTrigger value="model" icon={<Settings className="w-4 h-4" />}>
                Model Settings
              </TabsTrigger>
              <TabsTrigger value="prompt" icon={<MessageSquare className="w-4 h-4" />}>
                Prompts
              </TabsTrigger>
            </TabsList>

            {/* Knowledge Base Tab */}
            <TabsContent value="knowledge">
              <div className="space-y-6">
                <div className="flex items-center justify-between">
                  <div>
                    <h2 className="text-lg font-semibold text-[var(--color-gray-900)]">
                      Knowledge Base
                    </h2>
                    <p className="text-sm text-[var(--color-gray-500)]">
                      Manage documents that power your AI assistant
                    </p>
                  </div>
                  <Button icon={<Plus className="w-4 h-4" />}>
                    Create New
                  </Button>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  {knowledgeBases.map((kb) => (
                    <motion.div
                      key={kb.id}
                      initial={{ opacity: 0, y: 20 }}
                      animate={{ opacity: 1, y: 0 }}
                      whileHover={{ y: -4 }}
                    >
                      <Card hover className="relative">
                        <div className="flex items-start justify-between mb-4">
                          <div className="flex items-center gap-3">
                            <div
                              className={`w-10 h-10 rounded-xl flex items-center justify-center ${
                                kb.status === 'ready'
                                  ? 'bg-[var(--color-success)]/10 text-[var(--color-success)]'
                                  : kb.status === 'training'
                                  ? 'bg-[#667EEA]/10 text-[#667EEA]'
                                  : 'bg-[var(--color-error)]/10 text-[var(--color-error)]'
                              }`}
                            >
                              {kb.status === 'ready' ? (
                                <Check className="w-5 h-5" />
                              ) : kb.status === 'training' ? (
                                <RefreshCw className="w-5 h-5 animate-spin" />
                              ) : (
                                <AlertCircle className="w-5 h-5" />
                              )}
                            </div>
                            <div>
                              <h3 className="font-semibold text-[var(--color-gray-900)]">
                                {kb.name}
                              </h3>
                              <p className="text-sm text-[var(--color-gray-500)]">
                                {kb.description}
                              </p>
                            </div>
                          </div>
                          <Badge
                            variant={
                              kb.status === 'ready'
                                ? 'success'
                                : kb.status === 'training'
                                ? 'primary'
                                : 'error'
                            }
                          >
                            {kb.status}
                          </Badge>
                        </div>

                        {kb.status === 'training' && kb.progress && (
                          <div className="mb-4">
                            <Progress value={kb.progress} color="primary" showLabel />
                          </div>
                        )}

                        <div className="flex items-center justify-between text-sm text-[var(--color-gray-500)]">
                          <div className="flex items-center gap-4">
                            <span className="flex items-center gap-1">
                              <FileText className="w-4 h-4" />
                              {kb.documentCount} docs
                            </span>
                            <span>
                              Updated {kb.lastUpdated.toLocaleDateString()}
                            </span>
                          </div>
                          <div className="flex gap-2">
                            <button className="p-2 rounded-lg hover:bg-[var(--color-gray-100)] transition-colors">
                              <Upload className="w-4 h-4" />
                            </button>
                            <button className="p-2 rounded-lg hover:bg-[var(--color-error)]/10 text-[var(--color-error)] transition-colors">
                              <Trash2 className="w-4 h-4" />
                            </button>
                          </div>
                        </div>
                      </Card>
                    </motion.div>
                  ))}
                </div>
              </div>
            </TabsContent>

            {/* Model Settings Tab */}
            <TabsContent value="model">
              <div className="space-y-6">
                <div>
                  <h2 className="text-lg font-semibold text-[var(--color-gray-900)]">
                    Select AI Model
                  </h2>
                  <p className="text-sm text-[var(--color-gray-500)]">
                    Choose the AI model that powers your assistant
                  </p>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                  {aiModels.map((model) => (
                    <motion.div
                      key={model.id}
                      whileHover={{ scale: 1.02 }}
                      whileTap={{ scale: 0.98 }}
                    >
                      <Card
                        hover
                        className={`cursor-pointer ${
                          model.isSelected
                            ? 'ring-2 ring-[#667EEA] bg-[#667EEA]/5'
                            : ''
                        }`}
                      >
                        <div className="flex items-start justify-between mb-3">
                          <div
                            className={`w-10 h-10 rounded-xl flex items-center justify-center ${
                              model.id === 'gpt-4'
                                ? 'gradient-primary'
                                : model.id === 'gpt-3.5'
                                ? 'gradient-secondary'
                                : 'bg-gradient-to-br from-[#8B5CF6] to-[#EC4899]'
                            } text-white`}
                          >
                            {model.id === 'gpt-4' ? (
                              <Sparkles className="w-5 h-5" />
                            ) : model.id === 'gpt-3.5' ? (
                              <Zap className="w-5 h-5" />
                            ) : (
                              <Brain className="w-5 h-5" />
                            )}
                          </div>
                          {model.isSelected && (
                            <div className="w-6 h-6 rounded-full bg-[var(--color-success)] flex items-center justify-center">
                              <Check className="w-4 h-4 text-white" />
                            </div>
                          )}
                        </div>
                        <h3 className="font-semibold text-[var(--color-gray-900)] mb-1">
                          {model.name}
                        </h3>
                        <p className="text-sm text-[var(--color-gray-500)] mb-3">
                          {model.description}
                        </p>
                        <div className="flex flex-wrap gap-1">
                          {model.capabilities.map((cap, index) => (
                            <Badge key={index} variant="default" size="sm">
                              {cap}
                            </Badge>
                          ))}
                        </div>
                      </Card>
                    </motion.div>
                  ))}
                </div>

                <Card>
                  <h3 className="font-semibold text-[var(--color-gray-900)] mb-6">
                    Model Parameters
                  </h3>
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                    <Slider
                      label="Temperature"
                      value={modelConfig.temperature}
                      onChange={(v) =>
                        setModelConfig({ ...modelConfig, temperature: v })
                      }
                      min={0}
                      max={2}
                      step={0.1}
                    />
                    <Slider
                      label="Max Tokens"
                      value={modelConfig.maxTokens}
                      onChange={(v) =>
                        setModelConfig({ ...modelConfig, maxTokens: v })
                      }
                      min={256}
                      max={4096}
                      step={256}
                    />
                    <Slider
                      label="Top P"
                      value={modelConfig.topP}
                      onChange={(v) =>
                        setModelConfig({ ...modelConfig, topP: v })
                      }
                      min={0}
                      max={1}
                      step={0.1}
                    />
                    <Slider
                      label="Frequency Penalty"
                      value={modelConfig.frequencyPenalty}
                      onChange={(v) =>
                        setModelConfig({ ...modelConfig, frequencyPenalty: v })
                      }
                      min={0}
                      max={2}
                      step={0.1}
                    />
                  </div>
                </Card>
              </div>
            </TabsContent>

            {/* Prompts Tab */}
            <TabsContent value="prompt">
              <div className="space-y-6">
                <div>
                  <h2 className="text-lg font-semibold text-[var(--color-gray-900)]">
                    System Prompt
                  </h2>
                  <p className="text-sm text-[var(--color-gray-500)]">
                    Define the personality and behavior of your AI assistant
                  </p>
                </div>

                <Card>
                  <Textarea
                    value={systemPrompt}
                    onChange={(e) => setSystemPrompt(e.target.value)}
                    rows={12}
                    className="font-mono text-sm"
                  />
                  <div className="flex justify-between items-center mt-4">
                    <span className="text-sm text-[var(--color-gray-500)]">
                      {systemPrompt.length} characters
                    </span>
                    <div className="flex gap-2">
                      <Button variant="outline">Reset to Default</Button>
                      <Button>Save Changes</Button>
                    </div>
                  </div>
                </Card>

                <Card>
                  <h3 className="font-semibold text-[var(--color-gray-900)] mb-4">
                    Quick Templates
                  </h3>
                  <div className="grid grid-cols-1 md:grid-cols-3 gap-3">
                    {[
                      { name: 'Friendly', desc: 'Warm and casual tone' },
                      { name: 'Professional', desc: 'Formal business style' },
                      { name: 'Technical', desc: 'Detailed and precise' },
                    ].map((template) => (
                      <button
                        key={template.name}
                        className="p-4 rounded-xl border border-[var(--color-gray-200)] hover:border-[#667EEA] hover:bg-[#667EEA]/5 transition-colors text-left"
                      >
                        <p className="font-medium text-[var(--color-gray-900)]">
                          {template.name}
                        </p>
                        <p className="text-sm text-[var(--color-gray-500)]">
                          {template.desc}
                        </p>
                      </button>
                    ))}
                  </div>
                </Card>
              </div>
            </TabsContent>
          </Tabs>
        </div>

        {/* Test Panel */}
        <AnimatePresence>
          <motion.div
            initial={{ width: 0, opacity: 0 }}
            animate={{ width: 360, opacity: 1 }}
            exit={{ width: 0, opacity: 0 }}
            className="flex-shrink-0"
          >
            <Card className="h-[calc(100vh-140px)] flex flex-col !p-0 sticky top-0">
              <div className="p-4 border-b border-[var(--color-gray-100)]">
                <div className="flex items-center gap-2">
                  <TestTube className="w-5 h-5 text-[#667EEA]" />
                  <h3 className="font-semibold text-[var(--color-gray-900)]">
                    Test Panel
                  </h3>
                </div>
                <p className="text-sm text-[var(--color-gray-500)] mt-1">
                  Test your AI assistant configuration
                </p>
              </div>

              <div className="flex-1 overflow-y-auto p-4 space-y-4 bg-[var(--color-gray-50)]">
                {testConversation.map((msg, index) => (
                  <div
                    key={index}
                    className={`flex gap-2 ${
                      msg.role === 'user' ? 'flex-row-reverse' : ''
                    }`}
                  >
                    {msg.role === 'ai' ? (
                      <div className="w-8 h-8 rounded-full gradient-primary flex items-center justify-center flex-shrink-0">
                        <Bot className="w-4 h-4 text-white" />
                      </div>
                    ) : (
                      <Avatar name="User" size="sm" />
                    )}
                    <div
                      className={`max-w-[80%] px-4 py-2 rounded-2xl text-sm ${
                        msg.role === 'user'
                          ? 'gradient-primary text-white rounded-br-md'
                          : 'bg-white text-[var(--color-gray-900)] rounded-bl-md shadow-sm'
                      }`}
                    >
                      {msg.content}
                    </div>
                  </div>
                ))}
              </div>

              <div className="p-4 border-t border-[var(--color-gray-100)]">
                <div className="flex gap-2">
                  <input
                    type="text"
                    value={testInput}
                    onChange={(e) => setTestInput(e.target.value)}
                    onKeyDown={(e) => e.key === 'Enter' && handleSendTest()}
                    placeholder="Type a test message..."
                    className="flex-1 px-4 py-2 rounded-xl border border-[var(--color-gray-200)] text-sm focus:outline-none focus:ring-2 focus:ring-[#667EEA]"
                  />
                  <Button onClick={handleSendTest} size="sm">
                    <Send className="w-4 h-4" />
                  </Button>
                </div>
              </div>
            </Card>
          </motion.div>
        </AnimatePresence>
      </div>
    </MainLayout>
  );
}
